# Generated by Django 4.2.1 on 2023-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_stands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiestand",
            name="average_cookies_per_sale",
            field=models.IntegerField(default=0),
        ),
    ]
